### ISSUE TITLE
update doc

### ISSUE THREAD

**Issue by samburgers** [soberwp/unravel#1]
Hi, 

It appears to use the directory `acf/` rather than the documented`acf-json/`.

Cheers

**Comment by darrenjacoby** [comment]
Hi @samburgers 

The original folder is `acf-json/`, which is the default advanced custom fields folder.  Unravel moves and renames to `acf/` within `wp-content/models/`.

**Comment by samburgers** [comment]
Ah gotcha, thanks for the clarification. I was setting up from a fresh install, and was trying to just put the `acf-json/` folder straight into `web/app/models/` folder. Then i worked out i had to just put `acf-json/`  in the theme root first and let unravel copy it over. great work!
